version: '2'
services:
  mysqlmaster:
    image: mysql:5.7.15
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./data/mysql-master:/var/lib/mysql/
      - ./config/mysql-master:/etc/mysql/conf.d/
  mysqlslave:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./data/mysql-slave:/var/lib/mysql/
      - ./config/mysql-slave:/etc/mysql/conf.d/

  mysqlconfigure:
    image: mysql:5.7.15
    environment:
      - "MYSQL_MASTER_PASSWORD=root"
      - "MYSQL_SLAVE_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_REPLICATION_USER=kos"
      - "MYSQL_REPLICATION_PASSWORD=1111"
    volumes:
      - ./config_data.sh:/tmp/config_data.sh
    command: /bin/bash -x /tmp/config_data.sh

    

